---
- apt: name=postgresql-server-dev-{{ postgres_version }} # to build psycopg from source

- apt: name=postgresql-{{ postgres_version }}

- apt: name=python-psycopg2

- apt: name=python3-psycopg2

- postgresql_user: name={{ postgres_add_user }}
                   role_attr_flags=SUPERUSER
  become: yes
  become_user: postgres
